# Generated by Django 3.2.19 on 2023-11-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231117_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='img/channel_icon.jpg', upload_to='channel_images/'),
        ),
    ]
