# Generated by Django 3.2.19 on 2023-11-22 12:00

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_channel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='img/channel_icon.jpg', upload_to=main.models.channel_image_path),
        ),
    ]
