# Generated by Django 3.2.19 on 2024-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
