# Generated by Django 3.2.19 on 2024-01-30 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='joined_channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
