# Generated by Django 3.2.19 on 2024-01-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_channel_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='pin_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
